name: Timo
favicon: null
layout_spectrum: 0.012396324658766389
typography_spectrum: 0.1598855764605105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5198100791312754
  lightness: 0.40031392872333527
  saturation: 0.2810765935573727
  rhythmicContrast: 0.37875856598839164
purpose: []
